//! RINEX file parsing errors
use thiserror::Error;

use gnss_rs::{
    constellation::ParsingError as ConstellationParsingError, cospar::Error as CosparParsingError,
    domes::Error as DOMESParsingError, sv::ParsingError as SVParsingError,
};

use hifitime::{HifitimeError, ParsingError as HifitimeParsingError};

use std::io::Error as IoError;

use crate::hatanaka::CRX2RNXError;

mod meteo;
mod nav;
mod obs;

pub use meteo::MeteoRINEXParsingError;
pub use nav::NavRINEXParsingError;
pub use obs::ObsRINEXParsingError;

/// Errors that may rise in Parsing process
#[derive(Debug, Error)]
pub enum ParsingError {
    #[error("Invalid header line: too short")]
    HeaderLineTooShort,

    /// ANTEX (Antenna parameters record) are
    /// supported by a dedicated parser: https://github.com/nav-solutions/antex
    #[error("ANTEX format requires dedicated parser")]
    ANTEXFile,

    /// Errors raised during CRINEX file decompression process,
    /// not in the actual processing of the decompressed content.
    /// This is specific to CRINEX compressed files being seamlessly decompressed.
    /// These errors are either raised by:
    /// - a corruption or non supported case in the input file
    /// - a incorrect behavior of our CRINEX decompression implementation.
    #[error("CRX2RNX: {0}")]
    CRX2RNX(CRX2RNXError),

    #[error("NAV RINEX: {0}")]
    NavRINEXError(#[from] NavRINEXParsingError),

    #[error("OBS RINEX: {0}")]
    ObsRINEXError(#[from] ObsRINEXParsingError),

    #[error("Meteo RINEX: {0}")]
    MeteoRINEXError(#[from] MeteoRINEXParsingError),

    #[error("marker type")]
    MarkerType,

    #[error("nav: clock parsing")]
    ClockParsing,

    #[error("invalid epoch format")]
    EpochFormat,

    #[error("epoch parsing")]
    EpochParsing,

    #[error("datime parsing")]
    DatetimeParsing,

    #[error("datime invalid format")]
    DatetimeFormat,

    #[error("bad rinex revision format")]
    VersionFormat,

    #[error("rinex revision parsing")]
    VersionParsing,

    #[error("rinex format identification")]
    TypeParsing,

    #[error("constellation parsing")]
    ConstellationParsing(#[from] ConstellationParsingError),

    #[error("undefined constellation: bad header?")]
    UndefinedConstellation,

    #[error("sv parsing")]
    SVParsing(#[from] SVParsingError),

    #[error("cospar parsing")]
    COSPAR(#[from] CosparParsingError),

    #[error("clock TYPE OF DATA parsing")]
    ClockTypeofData,

    #[error("REF CLOCK OFFS parsing")]
    RcvClockOffsApplied,

    #[error("header coordinates parsing")]
    Coordinates,

    #[error("antenna coordinates parsing")]
    AntennaCoordinates,

    #[error("sensor coordinates parsing")]
    SensorCoordinates,

    #[error("non supported rinex revision")]
    NonSupportedVersion,

    #[error("unknown / non supported observable")]
    UnknownObservable,

    #[error("invalid leap second specs")]
    LeapFormat,

    #[error("leap second parsing")]
    LeapParsing,

    #[error("hifitime parsing")]
    HifitimeParsing(#[from] HifitimeParsingError),

    #[error("hifitime error")]
    Hifitime(#[from] HifitimeError),

    #[error("clock profile type parsing")]
    ClockProfileType,

    #[error("clock profile parsing")]
    ClockProfile,

    #[error("DOMES parsing")]
    DOMES(#[from] DOMESParsingError),

    #[error("obs: hardware events not supported yet")]
    ObsHardwareEvent,

    #[error("obs: bad v2 satellites description")]
    BadV2SatellitesDescription,

    #[error("bad utf-8 generated by CRINEX recovering process")]
    BadUtf8Crinex,
}

/// Errors that may rise in Formatting process
#[derive(Error, Debug)]
pub enum FormattingError {
    #[error("i/o: output error")]
    OutputError(#[from] IoError),

    #[error("missing constellation information")]
    UndefinedConstellation,

    #[error("missing navigation standard specs")]
    MissingNavigationStandards,

    #[error("undefined observables")]
    UndefinedObservables,

    #[error("missing observable definition")]
    MissingObservableDefinition,

    #[error("nav: unknown radio message")]
    NoNavigationDefinition,

    #[error("nav: missing grid defs")]
    NoGridDefinition,
}

/// General error (processing, analysis..)
#[derive(Debug)]
pub enum Error {
    /// Invalid frequency
    InvalidFrequency,

    /// Sampling Period is not determined
    UndeterminedSamplingPeriod,

    /// Unknown frequency
    UnknownFrequency,

    /// Non supported GPS [Observable]
    UnknownGPSObservable,

    /// Non supported Galileo [Observable]
    UnknownGalieoObservable,

    /// Non supported Glonass [Observable]
    UnknownGlonassObservable,

    /// Non supported QZSS [Observable]
    UnknownQZSSObservable,

    /// Non supported BDS [Observable]
    UnknownBeiDouObservable,

    /// Non supported IRNSS [Observable]
    UnknownIRNSSObservable,

    /// Non supported SBAS [Observable]
    UnknownSBASObservable,

    /// Non supported DORIS [Observable]
    UnknownDORISObservable,

    /// Unknown GPS Frequency
    UnknownGPSFrequency,

    /// Unknown Galileo Frequency
    UnknownGalileoFrequency,

    /// Unknown QZSS Frequency
    UnknownQzssFrequency,

    /// Unknown Glonass Frequency
    UnknownGlonassFrequency,

    /// Unknown BDS Frequency
    UnknownBDSFrequency,

    /// Unknown IRNSS Frequency
    UnknownIRNSSFrequency,

    /// Unknown SBAS Frequency
    UnknownSBASFrequency,

    /// Unknown DORIS Frequency
    UnknownDORISFrequency,
}
