//! R01 is a real record in the repository's public RINEX 4.02 fixture.
//! Numerical expectations are generated by tests/reference/glonass_fdma_r01.py,
//! which runs without the Rust library and follows the published RTKLIB model.
#![cfg(feature = "nav")]
use rinex::{
    navigation::rinex::{
        glonass_fdma::FdmaError,
        selection::{NativeFrame, NavRejection, UnknownHealthPolicy},
    },
    navigation::OrbitItem,
    prelude::{Duration, Epoch, Rinex, SV},
};
use std::str::FromStr;

fn sv() -> SV {
    SV::from_str("R01").unwrap()
}
fn fixture() -> Rinex {
    Rinex::from_file("data/NAV/V4/rinex402_examples_MN.rnx").unwrap()
}
fn reference() -> serde_json::Value {
    serde_json::from_str(include_str!("reference/glonass_fdma_r01.json")).unwrap()
}
fn epoch(rinex: &Rinex) -> Epoch {
    rinex
        .nav_ephemeris_frames_iter()
        .find(|(k, _)| k.sv == sv())
        .unwrap()
        .0
        .epoch
}
fn error_norm(a: [f64; 3], b: [f64; 3]) -> f64 {
    a.iter()
        .zip(b)
        .map(|(x, y)| (x - y).powi(2))
        .sum::<f64>()
        .sqrt()
}

#[test]
fn reference_epoch_preserves_state() {
    let rinex = fixture();
    let t = epoch(&rinex);
    let chosen = rinex.nav_select_glonass_fdma(sv(), t, UnknownHealthPolicy::Reject);
    let chosen = chosen.chosen().unwrap();
    let state = chosen.fdma_state_at(t).unwrap();
    let eph = chosen.ephemeris;
    assert_eq!(
        state.position_km,
        [
            eph.get_orbit_f64("satPosX").unwrap(),
            eph.get_orbit_f64("satPosY").unwrap(),
            eph.get_orbit_f64("satPosZ").unwrap()
        ]
    );
    assert_eq!(
        state.velocity_km_s,
        [
            eph.get_orbit_f64("velX").unwrap(),
            eph.get_orbit_f64("velY").unwrap(),
            eph.get_orbit_f64("velZ").unwrap()
        ]
    );
    assert_eq!(state.frame, NativeFrame::GlonassBroadcastPz90);
    assert_eq!(state.clock_correction_s, chosen.ephemeris.clock_bias);
    assert_eq!(chosen.ephemeris.glonass_freq_channel(), Some(1));
}

#[test]
fn forward_backward_matches_reference() {
    let rinex = fixture();
    let t0 = epoch(&rinex);
    let reference = reference();
    assert_eq!(
        reference["input_sha256"],
        "ba4b549010bc97eaf61c6102a09052668d3b29c423688f6bc5b4b30f7e433442"
    );
    let mut max_position_error_km: f64 = 0.0;
    let mut max_velocity_error_km_s: f64 = 0.0;
    for dt in [0.0, 60.0, -60.0, 300.0, -300.0, 899.5, -899.5] {
        let t = t0 + Duration::from_seconds(dt);
        let selection = rinex.nav_select_glonass_fdma(sv(), t, UnknownHealthPolicy::Reject);
        let state = selection.chosen().unwrap().fdma_state_at(t).unwrap();
        let expected = reference["state_km_km_s"][dt.to_string()]
            .as_array()
            .unwrap();
        for (i, actual) in state
            .position_km
            .iter()
            .chain(state.velocity_km_s.iter())
            .enumerate()
        {
            let gold = expected[i].as_f64().unwrap();
            let tolerance = if i < 3 { 1e-8 } else { 1e-10 };
            if i < 3 {
                max_position_error_km = max_position_error_km.max((actual - gold).abs());
            } else {
                max_velocity_error_km_s = max_velocity_error_km_s.max((actual - gold).abs());
            }
            assert!(
                (actual - gold).abs() < tolerance,
                "dt={dt} component={i} got={actual} gold={gold}"
            );
        }
    }
    println!("max position error: {max_position_error_km:.3e} km; max velocity error: {max_velocity_error_km_s:.3e} km/s");
}

#[test]
fn step_refinement_converges() {
    let rinex = fixture();
    let t = epoch(&rinex) + Duration::from_seconds(899.5);
    let selection = rinex.nav_select_glonass_fdma(sv(), t, UnknownHealthPolicy::Reject);
    let chosen = selection.chosen().unwrap();
    let s60 = chosen.fdma_state_at_with_step(t, 60.0).unwrap();
    let s30 = chosen.fdma_state_at_with_step(t, 30.0).unwrap();
    let s15 = chosen.fdma_state_at_with_step(t, 15.0).unwrap();
    let coarse = error_norm(s60.position_km, s30.position_km);
    let fine = error_norm(s30.position_km, s15.position_km);
    assert!(fine < coarse, "coarse={coarse} fine={fine}");
    assert!(coarse < 1e-5, "coarse km={coarse}");
    println!("step refinement: |60-30|={coarse:.3e} km; |30-15|={fine:.3e} km");
    assert_eq!(
        chosen.fdma_state_at_with_step(t, 0.0).unwrap_err(),
        FdmaError::InvalidStep
    );
}

#[test]
fn missing_acceleration_is_not_zero() {
    let mut rinex = fixture();
    let t = epoch(&rinex);
    let (_, frame) = rinex
        .record
        .as_mut_nav()
        .unwrap()
        .iter_mut()
        .find(|(k, _)| k.sv == sv())
        .unwrap();
    frame.as_mut_ephemeris().unwrap().orbits.remove("accelY");
    let selection = rinex.nav_select_glonass_fdma(sv(), t, UnknownHealthPolicy::Reject);
    assert_eq!(
        selection.candidates[0].rejection,
        Some(NavRejection::MissingOrbitField)
    );
    assert_eq!(
        selection.candidates[0].fdma_state_at(t).unwrap_err(),
        FdmaError::MissingField("accelY")
    );
    assert_eq!(
        selection.candidates[0].fdma_clock_correction_s(t).unwrap(),
        6.761029362679e-05
    );
    // An explicitly present zero is a valid perturbation component.
    let mut rinex = fixture();
    let (_, frame) = rinex
        .record
        .as_mut_nav()
        .unwrap()
        .iter_mut()
        .find(|(k, _)| k.sv == sv())
        .unwrap();
    let eph = frame.as_mut_ephemeris().unwrap();
    eph.orbits.insert("accelY".into(), 0.0.into());
    eph.orbits.insert("channel".into(), OrbitItem::I8(0));
    assert_eq!(eph.glonass_freq_channel(), Some(0));
    assert!(rinex
        .nav_select_glonass_fdma(sv(), t, UnknownHealthPolicy::Reject)
        .chosen()
        .unwrap()
        .fdma_state_at(t)
        .is_ok());
}

#[test]
fn equivalent_timescales_agree() {
    let rinex = fixture();
    let utc = epoch(&rinex) + Duration::from_seconds(300.0);
    let gpst = utc.to_time_scale(rinex::prelude::TimeScale::GPST);
    let selection = rinex.nav_select_glonass_fdma(sv(), utc, UnknownHealthPolicy::Reject);
    let chosen = selection.chosen().unwrap();
    let a = chosen.fdma_state_at(utc).unwrap();
    let b = chosen.fdma_state_at(gpst).unwrap();
    assert_eq!(a.position_km, b.position_km);
    assert_eq!(a.velocity_km_s, b.velocity_km_s);
    assert_eq!(a.clock_correction_s, b.clock_correction_s);
}

#[test]
fn synthetic_cross_midnight_keeps_elapsed_time() {
    let original = fixture();
    let t0 = epoch(&original);
    let original_t = t0 + Duration::from_seconds(600.0);
    let original_selection =
        original.nav_select_glonass_fdma(sv(), original_t, UnknownHealthPolicy::Reject);
    let expected = original_selection
        .chosen()
        .unwrap()
        .fdma_state_at(original_t)
        .unwrap();

    // Synthetic change of only the record epoch: 23:55 + 600 s = next day.
    let mut shifted = fixture();
    let nav = shifted.record.as_mut_nav().unwrap();
    let (key, frame) = nav
        .iter()
        .find(|(key, _)| key.sv == sv())
        .map(|(key, frame)| (*key, frame.clone()))
        .unwrap();
    nav.remove(&key);
    let mut new_key = key;
    new_key.epoch += Duration::from_seconds(600.0);
    nav.insert(new_key, frame);
    let t = new_key.epoch + Duration::from_seconds(600.0);
    assert!(t.to_string().contains("2020-09-16"));
    let selection = shifted.nav_select_glonass_fdma(sv(), t, UnknownHealthPolicy::Reject);
    let state = selection.chosen().unwrap().fdma_state_at(t).unwrap();
    assert_eq!(state.position_km, expected.position_km);
    assert_eq!(state.velocity_km_s, expected.velocity_km_s);
    assert_eq!(state.clock_correction_s, expected.clock_correction_s);
}

#[test]
fn fdma_clock_does_not_use_frame_time_as_a2() {
    let mut rinex = fixture();
    let t0 = epoch(&rinex);
    let (_, frame) = rinex
        .record
        .as_mut_nav()
        .unwrap()
        .iter_mut()
        .find(|(k, _)| k.sv == sv())
        .unwrap();
    let eph = frame.as_mut_ephemeris().unwrap();
    eph.clock_drift = 2.0e-11;
    eph.clock_drift_rate = 500_000.0; // synthetic frame time; not quadratic drift
    let t = t0 + Duration::from_seconds(300.0);
    let selection = rinex.nav_select_glonass_fdma(sv(), t, UnknownHealthPolicy::Reject);
    let chosen = selection.chosen().unwrap();
    assert_eq!(chosen.ephemeris.clock_drift_rate, 500_000.0);
    let got = chosen.fdma_state_at(t).unwrap().clock_correction_s;
    assert!((got - (eph_clock_bias() + 2.0e-11 * 300.0)).abs() < 1e-15);
}
fn eph_clock_bias() -> f64 {
    6.761029362679e-05
}

#[test]
fn expired_record_rejected() {
    let rinex = fixture();
    let t0 = epoch(&rinex);
    for dt in [-900.0, 900.0] {
        let t = t0 + Duration::from_seconds(dt);
        let selection = rinex.nav_select_glonass_fdma(sv(), t, UnknownHealthPolicy::Reject);
        assert!(selection.chosen().is_none());
        assert_eq!(
            selection.candidates[0].rejection,
            Some(NavRejection::OutOfValidity)
        );
        assert_eq!(
            selection.candidates[0].fdma_state_at(t).unwrap_err(),
            FdmaError::OutOfValidity
        );
    }
}

#[test]
fn cdma_message_is_not_fdma() {
    let rinex = fixture();
    let sv = SV::from_str("R26").unwrap();
    let t = rinex
        .nav_ephemeris_frames_iter()
        .find(|(key, _)| key.sv == sv)
        .unwrap()
        .0
        .epoch;
    let selection = rinex.nav_select_glonass_fdma(sv, t, UnknownHealthPolicy::Reject);
    assert!(selection.chosen().is_none());
    assert_eq!(
        selection.candidates[0].rejection,
        Some(NavRejection::UnsupportedMessage)
    );
    assert_eq!(
        selection.candidates[0].fdma_state_at(t).unwrap_err(),
        FdmaError::UnsupportedMessage
    );
}

#[test]
fn nearer_unpropagatable_record_cannot_displace_fdma() {
    let mut rinex = fixture();
    let t0 = epoch(&rinex);
    let (key, frame) = rinex
        .record
        .as_nav()
        .unwrap()
        .iter()
        .find(|(key, _)| key.sv == sv())
        .map(|(key, frame)| (*key, frame.clone()))
        .unwrap();
    let t = t0 + Duration::from_seconds(300.0);
    let mut nearer = key;
    nearer.epoch = t;
    let mut bad = frame;
    for field in ["satPosX", "satPosY", "satPosZ"] {
        bad.as_mut_ephemeris()
            .unwrap()
            .orbits
            .insert(field.into(), 1.0.into()); // Synthetic inside-Earth radius.
    }
    rinex.record.as_mut_nav().unwrap().insert(nearer, bad);
    let selection = rinex.nav_select_glonass_fdma(sv(), t, UnknownHealthPolicy::Reject);
    assert_eq!(selection.chosen().unwrap().key, &key);
    assert!(selection.candidates.iter().any(|candidate| {
        candidate.key == &nearer && candidate.rejection == Some(NavRejection::Unpropagatable)
    }));
}

#[test]
fn health_and_data_validity_reject_even_at_reference_epoch() {
    let mut rinex = fixture();
    let t = epoch(&rinex);
    let key = *rinex
        .nav_ephemeris_frames_iter()
        .find(|(key, _)| key.sv == sv())
        .unwrap()
        .0;
    let eph = rinex
        .record
        .as_mut_nav()
        .unwrap()
        .get_mut(&key)
        .unwrap()
        .as_mut_ephemeris()
        .unwrap();
    eph.orbits.remove("health");
    assert_eq!(
        rinex
            .nav_select_glonass_fdma(sv(), t, UnknownHealthPolicy::Reject)
            .candidates[0]
            .rejection,
        Some(NavRejection::UnknownHealth)
    );
    assert!(rinex
        .nav_select_glonass_fdma(sv(), t, UnknownHealthPolicy::Allow)
        .chosen()
        .is_some());
    rinex
        .record
        .as_mut_nav()
        .unwrap()
        .get_mut(&key)
        .unwrap()
        .as_mut_ephemeris()
        .unwrap()
        .orbits
        .insert("dataValidity".into(), 1.0.into());
    assert_eq!(
        rinex
            .nav_select_glonass_fdma(sv(), t, UnknownHealthPolicy::Allow)
            .candidates[0]
            .rejection,
        Some(NavRejection::InvalidData)
    );
}

#[test]
fn legacy_v2_and_v3_glonass_records_propagate_at_reference() {
    for file in [
        "data/NAV/V2/amel0010.21g",
        "data/NAV/V3/MOJN00DNK_R_20201770000_01D_MN.rnx.gz",
    ] {
        let nav = if file.ends_with(".gz") {
            Rinex::from_gzip_file(file).unwrap()
        } else {
            Rinex::from_file(file).unwrap()
        };
        let selected = nav
            .nav_ephemeris_frames_iter()
            .filter(|(key, _)| key.sv.constellation == rinex::prelude::Constellation::Glonass)
            .find_map(|(key, _)| {
                let report =
                    nav.nav_select_glonass_fdma(key.sv, key.epoch, UnknownHealthPolicy::Reject);
                report.chosen().and_then(|chosen| {
                    chosen
                        .fdma_state_at(key.epoch)
                        .ok()
                        .map(|state| (chosen.key.msgtype, state))
                })
            });
        let (message, state) =
            selected.unwrap_or_else(|| panic!("no propagatable GLONASS in {file}"));
        assert_eq!(message, rinex::navigation::NavMessageType::LNAV);
        assert_eq!(state.frame, NativeFrame::GlonassBroadcastPz90);
    }
}
