name: CI

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0
    
    - uses: actions-rs/cargo@v1
      name: Linter 
      with:
        command: fmt
        args: --all -- --check
    
    - uses: actions-rs/toolchain@v1
      name: Install Rust
      with:
        toolchain: stable
        override: true
    
    - uses: actions-rs/cargo@v1
      name: Build (default)
      with:
        command: build
        args: -r
    
    - uses: actions-rs/cargo@v1
      name: Clean
      with:
        command: clean
    
    - uses: actions-rs/cargo@v1
      name: Build (all features)
      with:
        command: build
        args: --all-features
    
    - uses: actions-rs/cargo@v1
      name: Clean
      with:
        command: clean
    
    - uses: actions-rs/cargo@v1
      name: Build (Observation)
      with:
        command: build
        args: --features obs
    
    - uses: actions-rs/cargo@v1
      name: Clean
      with:
        command: clean
    
    - uses: actions-rs/cargo@v1
      name: Build (Navigation)
      with:
        command: build
        args: --features nav
    
    - uses: actions-rs/cargo@v1
      name: Clean
      with:
        command: clean
    
    - uses: actions-rs/cargo@v1
      name: Build (Meteo)
      with:
        command: build
        args: --features meteo
    
    - uses: actions-rs/cargo@v1
      name: Clean
      with:
        command: clean
    
    - uses: actions-rs/cargo@v1
      name: Build (Clock)
      with:
        command: build
        args: --features clock
    
    - uses: actions-rs/cargo@v1
      name: Clean
      with:
        command: clean
    
    - uses: actions-rs/cargo@v1
      name: Build (DORIS)
      with:
        command: build
        args: --features doris
    
    - uses: actions-rs/cargo@v1
      name: Clean
      with:
        command: clean
    
    - uses: actions-rs/cargo@v1
      name: Build (ANTEX)
      with:
        command: build
        args: --features antex

    - uses: actions-rs/cargo@v1
      name: Clean
      with:
        command: clean
    
    - uses: actions-rs/cargo@v1
      name: Build (Qc)
      with:
        command: build
        args: --features qc
    
    - uses: actions-rs/cargo@v1
      name: Clean
      with:
        command: clean
    
    - uses: actions-rs/cargo@v1
      name: Build (Processing)
      with:
        command: build
        args: --features processing
    
    - uses: actions-rs/cargo@v1
      name: Clean
      with:
        command: clean
    
    - uses: actions-rs/cargo@v1
      name: Test (all features)
      with:
        command: test
        args: --all-features
    
  documentation:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0
    
    - uses: actions-rs/toolchain@v1
      name: Install nightly
      with:
        toolchain: nightly
        override: true
    
    - name: Documentation
      run: |
        ./tools/builddoc.sh
